version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - ollama

  worker:
    build: .
    command: celery -A campusconnect worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=campusconnect
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      serve 
      --threads 16 
      --parallel 4 
      --mmap
    environment:
      - OLLAMA_DEBUG=INFO
    networks:
      - default


volumes:
  postgres_data:
  ollama_data:
